// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRuobeDGgJh8H5iDWY4mXT0gU4ZOZs1w',
    appId: '1:237365930263:web:6b56489657b235df3b2f52',
    messagingSenderId: '237365930263',
    projectId: 'todolist-9bebd',
    authDomain: 'todolist-9bebd.firebaseapp.com',
    storageBucket: 'todolist-9bebd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFYGKbTwJTibanHjqYS-_LXox10rQJu0o',
    appId: '1:237365930263:android:175f83f785d4e6693b2f52',
    messagingSenderId: '237365930263',
    projectId: 'todolist-9bebd',
    storageBucket: 'todolist-9bebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxW2M9W2V8kzDMpPQoLLUby7kxOkfmOPo',
    appId: '1:237365930263:ios:2732b24e5e2b42293b2f52',
    messagingSenderId: '237365930263',
    projectId: 'todolist-9bebd',
    storageBucket: 'todolist-9bebd.appspot.com',
    iosBundleId: 'com.mrdamos69.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxW2M9W2V8kzDMpPQoLLUby7kxOkfmOPo',
    appId: '1:237365930263:ios:30140b8b00dcf0b83b2f52',
    messagingSenderId: '237365930263',
    projectId: 'todolist-9bebd',
    storageBucket: 'todolist-9bebd.appspot.com',
    iosBundleId: 'com.mrdamos69.todolist.RunnerTests',
  );
}
